{
 "openapi": "3.1.0",
 "info": {
  "title": "Lost Communities",
  "version": "0.0.1",
  "description": "Kansas Lost Communities Project"
 },
 "servers": [
  {
   "url": "https://verbose-rotary-phone-4j7j6p6v4xxhq6r6-3000.app.github.dev"
  }
 ],
 "paths": {
  "/api/": {
   "get": {
    "summary": "list API versions",
    "tags": [
     "api"
    ]
   }
  },
  "/auth/bypass": {
   "get": {
    "summary": "bypass authentication for testing",
    "description": "Bypasses CAS authentication for testing purposes",
    "tags": [
     "auth"
    ]
   }
  },
  "/auth/cas": {
   "get": {
    "summary": "CAS authentication",
    "description": "CAS authentication for deployment",
    "tags": [
     "auth"
    ]
   }
  },
  "/auth/token": {
   "get": {
    "summary": "request JWT",
    "description": "request JWT based on previous authentication",
    "tags": [
     "auth"
    ]
   }
  },
  "/auth/logout": {
   "get": {
    "summary": "logout current user",
    "description": "logout current user and end session",
    "tags": [
     "auth"
    ]
   }
  },
  "/": {
   "get": {
    "summary": "index page",
    "description": "Gets the index page for the application",
    "tags": [
     "index"
    ]
   }
  },
  "/api/v1/communities": {
   "get": {
    "summary": "communities list page",
    "description": "Gets the list of all communities in the application",
    "tags": [
     "communities"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_communities",
       "manage_communities",
       "add_communitiies"
      ]
     }
    ]
   },
   "post": {
    "summary": "create community",
    "tags": [
     "communities"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_communities",
       "add_communitiies"
      ]
     }
    ]
   }
  },
  "/api/v1/communities/{id}": {
   "get": {
    "summary": "get single community",
    "description": "Gets a single community by ID",
    "tags": [
     "communities"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_communities",
       "manage_communities",
       "add_communitiies"
      ]
     }
    ]
   },
   "put": {
    "summary": "update community",
    "tags": [
     "communities"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_communities"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete community",
    "tags": [
     "communities"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_communities"
      ]
     }
    ]
   }
  },
  "/api/v1/counties": {
   "get": {
    "summary": "counties list page",
    "description": "Gets the list of all counties in the application",
    "tags": [
     "counties"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_communities",
       "manage_communities",
       "add_communitiies"
      ]
     }
    ]
   }
  },
  "/api/v1/documents": {
   "get": {
    "summary": "documents list page",
    "description": "Gets the list of all documents in the application",
    "tags": [
     "documents"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_documents",
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   },
   "post": {
    "summary": "create document",
    "tags": [
     "documents"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/documents/{id}": {
   "get": {
    "summary": "get single document",
    "description": "Gets a single document by ID",
    "tags": [
     "documents"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_documents",
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   },
   "put": {
    "summary": "update document",
    "tags": [
     "documents"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete document",
    "tags": [
     "documents"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/documents/{id}/upload": {
   "post": {
    "summary": "upload document",
    "tags": [
     "documents"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/metadata": {
   "get": {
    "summary": "metadata list page",
    "description": "Gets the list of all metadata in the application",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_documents",
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   },
   "post": {
    "summary": "create metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/metadata/{id}": {
   "get": {
    "summary": "get single metadata",
    "description": "Gets a single metadata item by ID",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "view_documents",
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   },
   "put": {
    "summary": "create metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/metadata/{id}/add_document": {
   "post": {
    "summary": "add document to metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/metadata/{id}/remove_document": {
   "post": {
    "summary": "remove document from metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/metadata/{id}/add_community": {
   "post": {
    "summary": "add community to metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/metadata/{id}/remove_community": {
   "post": {
    "summary": "remove community from metadata",
    "tags": [
     "metadata"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_documents",
       "add_documents"
      ]
     }
    ]
   }
  },
  "/api/v1/roles": {
   "get": {
    "summary": "roles list page",
    "description": "Gets the list of all roles in the application",
    "tags": [
     "roles"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   }
  },
  "/api/v1/users": {
   "get": {
    "summary": "users list page",
    "description": "Gets the list of all users in the application",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   },
   "post": {
    "summary": "create user",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   }
  },
  "/api/v1/users/{id}": {
   "get": {
    "summary": "get single user",
    "description": "Gets a single user by ID",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   },
   "put": {
    "summary": "update user",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   },
   "delete": {
    "summary": "delete user",
    "tags": [
     "users"
    ],
    "security": [
     {
      "bearerAuth": [
       "manage_users"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "bearerAuth": {
    "type": "http",
    "scheme": "bearer",
    "bearerFormat": "JWT"
   }
  }
 },
 "tags": [
  {
   "name": "api",
   "description": "API routes"
  },
  {
   "name": "auth",
   "description": "Authentication Routes"
  },
  {
   "name": "index",
   "description": "Index Routes"
  },
  {
   "name": "users",
   "description": "Users Routes"
  },
  {
   "name": "communities",
   "description": "Communities Routes"
  },
  {
   "name": "counties",
   "description": "Counties Routes"
  },
  {
   "name": "documents",
   "description": "Documents Routes"
  },
  {
   "name": "metadata",
   "description": "Metadata Routes"
  },
  {
   "name": "roles",
   "description": "Roles Routes"
  }
 ]
}